### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by astraw** [BrainsOnBoard/compound-ray#22]
Hi, this and your preprint look really interesting and I would really like to try this out. The build instructions in the README, however, start already by mentioning a path which doesn't exist. Would you be able to touch up the existing documentation, starting with the README, about how to build the software? Is this primarily developed on one particular OS? What specific version of OptiX and CUDA has been tested?

Thanks!

**Comment by Blayzeing** [comment]
Hi,

Sorry about that - it seems the markdown parser was hiding the "<make or ninja>" part of the path - you should be able to build using the commands found [here](https://github.com/ManganLab/eye-renderer/tree/master/build/make), although see additional details [here](https://github.com/ManganLab/eye-renderer/blob/master/build/build-notes.txt). I've also updated the main readme with additional details about the versions of the OptiX SDK and Cuda required and OS I've been building on.

Any other questions, don't hesitate to reply here. I'll be re-building the tool on a fresh install myself in a few days, so I will be able to re-create anything that might be more tricky to narrow down then.

**Comment by Blayzeing** [comment]
In the process of testing the new in-depth build documentation I have just run into a similar problem to the one you outlined in [your comment](https://github.com/ManganLab/eye-renderer/issues/22#issuecomment-941164791), which turned out to be because some of cc's internal libraries were unlinked when being switched through `update-alternatives` on the system I was testing it on. The added [troubleshooting section](https://github.com/ManganLab/eye-renderer/issues/22#issuecomment-941164791) shows the error I received and the steps I took to work around it. It boiled down to force reinstalling `build-essential` then checking the installation statuses of `gcc-8` and `g++-8` and then re-running
```
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 8
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 8
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 9
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 9
```
to ensure that update-alternatives was linking to the correct binaries.

**Comment by astraw** [comment]
Thanks for the updates. Sorry I was quite busy and only had a chance to check this now. It seems to be working. I'm not sure what key step I was missing but your new documentation got it working for me. Thanks again.

![image](https://user-images.githubusercontent.com/30176/142203000-0810bb4f-0501-4667-a209-e12575b8c902.png)
